# Generated by Django 4.1.7 on 2023-07-31 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0001_m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="sharee",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="sharee",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="shared_dashboard",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
