# Generated by Django 4.1.7 on 2023-07-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="settings",
            field=models.JSONField(default={}),
        ),
    ]
