# Generated by Django 4.1.7 on 2023-11-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="settings",
            field=models.JSONField(default=dict),
        ),
    ]
