# Generated by Django 4.1.7 on 2023-02-15 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    def forward_run(apps, _):  # sourcery skip: instance-method-first-arg-name
        Package = apps.get_model("accounts", "Package")
        Package.objects.create(
            name="Package 1", description="All lenders have this init package"
        )

    def backward_run(apps, _):  # sourcery skip: instance-method-first-arg-name
        Package = apps.get_model("accounts", "Package")
        Package.objects.filter(
            name="Package 1", description="All lenders have this init package"
        ).delete()

    operations = [migrations.RunPython(forward_run, backward_run)]
