# Generated by Django 4.1.7 on 2023-02-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auto_20230215_1702"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowerprofile",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Lender"), (1, "Bureauer"), (2, "Admin")]
            ),
        ),
    ]
