# Generated by Django 4.1.7 on 2023-02-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_borrowerprofile_created_borrowerprofile_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lender",
            name="public",
            field=models.CharField(
                max_length=150, verbose_name="Public key for encrypting user data"
            ),
        ),
        migrations.AlterField(
            model_name="lender",
            name="secret",
            field=models.CharField(
                max_length=150,
                verbose_name="Secret key for decrypting user data passed across",
            ),
        ),
    ]
