# Generated by Django 4.1.7 on 2023-03-04 01:42

from django.db import migrations

PACKAGE_LIST = ["Basic", "Premium"]


def forward_func(apps, _):
    Package = apps.get_model("accounts", "Package")
    Package.objects.bulk_create([Package(name=package) for package in PACKAGE_LIST])


def backward_func(apps, _):
    Package = apps.get_model("accounts", "Package")
    Package.objects.filter(name__in=PACKAGE_LIST).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_m"),
    ]

    operations = [migrations.RunPython(forward_func, backward_func)]
