# Generated by Django 4.1.7 on 2023-05-29 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lender",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="lender",
            name="public",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                verbose_name="Public key for encrypting user data",
            ),
        ),
    ]
