# Generated by Django 4.1.7 on 2023-06-14 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_m"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ("created",)},
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
