# Generated by Django 4.1.7 on 2023-07-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lender",
            name="secret",
            field=models.CharField(
                default="",
                max_length=150,
                verbose_name="Secret key for decrypting user data passed across",
            ),
        ),
    ]
