# Generated by Django 4.1.7 on 2023-11-20 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_m"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
