FROM node:19.7 AS frontend-development

WORKDIR /app/SPA

COPY ./SPA/package.json ./SPA/package-lock.json ./SPA/.env ./SPA/.npmrc ./SPA/config-overrides.js /app/SPA/

RUN npm install
COPY ./SPA /app/SPA

RUN npm run build

WORKDIR /app/SPA

ENTRYPOINT ["node"]
