# Generated by Django 4.1.7 on 2023-02-19 13:29
from django.contrib.auth.models import Group
from django.db import migrations


def forward_func(apps, _):
    Group.objects.create(name="Lender's Admin")


def backward_func(apps, _):
    Group.objects.filter(name="Lender's Admin").delete()


class Migration(migrations.Migration):
    dependencies = []

    operations = [migrations.RunPython(forward_func, backward_func)]
